# Generated by Django 3.0.4 on 2020-03-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygrometer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hygrometer',
            name='type',
        ),
        migrations.AlterField(
            model_name='hygrometer',
            name='value',
            field=models.IntegerField(verbose_name='Humedad'),
        ),
    ]
