# Generated by Django 3.0.6 on 2020-05-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygrometer', '0003_hygrometer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hygrometer',
            name='ground',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hygrometer',
            name='latitude',
            field=models.FloatField(default=0, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='hygrometer',
            name='length',
            field=models.FloatField(default=0, verbose_name='Longitud'),
        ),
    ]
